### ISSUE TITLE
Tex/Latex is a requirement

### ISSUE THREAD

**Issue by dgoppenheimer** [Joseph-Ellaway/Ramachandran_Plotter#4]
**Describe the bug**
The plot is not drawn because latex could not be found.

**To Reproduce**
1. Go to Google Colab
2. install dependencies:
`!pip install numpy pandas matplotlib scipy biopython matplotlib argparse opencv-python`
3. fetch a `.pdb` file:
`!wget https://files.rcsb.org/download/6GVE.pdb`
4. Install Ramachandran_Plotter:
`!git clone https://github.com/Joseph-Ellaway/Ramachandran_Plotter.git`
5. Change directory:
`%cd Ramachandran_Plotter` and move 6GVE.pdb into the directory.
6. Run program:
`!python RamachandranPlotter.py --pdb 6GVE.pdb --plot_type 0`
8. See error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/texmanager.py", line 306, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'
```

**Expected behavior**
The plot should be drawn.

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser [chrome]

**Additional context**
 I assume that Latex is used to draw the phi and psi symbols. It may be more universal to use the ASCI codes ( u03A6, u03A8).

**Comment by Joseph-Ellaway** [comment]
Hi David G. Oppenheimer, 

Thanks for opening the issue and giving such a detailed report on the problem. I think the issue has now been patched, using the unicode chars instead of the LaTeX feature set from Matplotlib. I have also included a test PDB file in `example_data`, which you might find useful for testing purposes.  

Let me know if you're having any further issues.
